##############ATR_TARGET#############
# WGRIFFITH2 (C) 2013

INPUT ATR = 3.5;
INPUT PERIODS = 7;

DEF ROLLINGLOW = LOWEST(DATA = LOW(), LENGTH = PERIODS)[-1];
DEF TARGET = ROLLINGLOW + ATRWILDER()*ATR;

PLOT PLOT_TARGET = TARGET;

PLOT_TARGET.SETDEFAULTCOLOR(CREATECOLOR(11, 0, 78));

#####################################