##############ATR_TARGET#############
# WGRIFFITH2 (C) 2013

INPUT FACTOR = 3;
INPUT PERIODS = 3;

DEF ROLLINGLOW = LOWEST(DATA = LOW(), LENGTH = PERIODS)[1];
DEF TARGET = ROLLINGLOW + ATRWILDER()*FACTOR;

PLOT PLOT_TARGET = TARGET;

PLOT_TARGET.SETDEFAULTCOLOR(CREATECOLOR(0, 255, 0));
PLOT_TARGET.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.POINTS);

#####################################