##############CANDLESTICKER###############
# WGRIFFITH2 (C) 2013

#HTTP://WWW.CANDLESTICKER.COM/PATTERN.ASPX?LANG=EN&PATTERN=2111
DEF KPERIOD = 14;
DEF DPERIOD = 3;

DEF FASTLINE = ROUND(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD));

DEF SLOWLINE = ROUND(SIMPLEMOVINGAVG(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD), LENGTH = DPERIOD));

DEF ONEWHITESOLDIER = (OPEN[1]-CLOSE[1])/(.001+(HIGH[1]-LOW[1]))>0.6 AND (CLOSE-OPEN)/(.001+(HIGH-LOW))>0.6 AND (CLOSE[1]<OPEN) AND (OPEN[1] > OPEN) AND (OPEN[1]<CLOSE);

DEF CANDLESTICKER = ABANDONEDBABY().BULLISH OR DOJI() OR ENGULFING().BULLISH OR HAMMER() OR HARAMI().BULLISH OR HARAMICROSS().BULLISH OR KICKING().BULLISH OR MARUBOZU().BULLISH OR MEETINGLINES().BULLISH OR MORNINGDOJISTAR() OR MORNINGSTAR() OR ONEWHITESOLDIER IS TRUE OR PIERCINGLINE() OR THREEINSIDEUP() OR THREEOUTSIDEUP() OR  THREEStarsInTheSouth() OR THREEWHITESOLDIERS() OR UNIQUeThreeRiverBottom();
DEF ENTRY = CANDLESTICKER IS TRUE AND SLOWLINE <=35;
PLOT ABOVE = ENTRY;

ABOVE.SetDefaultColor(CreateColor(255, 247, 0));
ABOVE.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_UP);

#########################################