# CANDLESTICKER
# WGRIFFITH2 (C) 2013

DEF KPERIOD = 14;
DEF DPERIOD = 3;
DEF FASTLINE = ROUND(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD));

DEF SLOWLINE = ROUND(SIMPLEMOVINGAVG(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD), LENGTH = DPERIOD));

DEF CANDLESTICKER = KICKING().BULLISH OR MORNINGSTAR() OR PIERCINGLINE() OR THREEINSIDEUP() OR THREEOUTSIDEUP() OR THREEWHITESOLDIERS();
DEF ENTRY = CANDLESTICKER IS TRUE AND FASTLINE <=40 AND FASTLINE >= SLOWLINE;
PLOT ABOVE = ENTRY;

ABOVE.SetDefaultColor(CreateColor(255, 247, 0));
ABOVE.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_UP);

#########################################