# CHANDELIEREXIT
# WGRIFFITH2 (C) 2013

input LENG = 22;
input MULT = 3;

DEF LONG_EXIT = HIGHEST(DATA = HIGH(), LENGTH = LENG) - (ATRWilder(LENG) * MULT);
PLOT BELOW = LONG_EXIT;
BELOW.SETDEFAULTCOLOR(CREATECOLOR(11, 0, 78));