# DMI_ReversalTrigger
# WGRIFFITH2 (C) 2014

INPUT LENGTH = 10;
INPUT KPERIOD = 14;
INPUT DPERIOD = 3;
INPUT OVER_BOUGHT = 90;
INPUT OVER_SOLD = 10;

DEF DMISTOCH = DMI_STOCHASTICEXTREME(LENGTH, KPERIOD, DPERIOD, OVER_BOUGHT, OVER_SOLD);

plot LONG = DMISTOCH CROSSES ABOVE OVER_SOLD;

plot SHORT = DMISTOCH CROSSES BELOW OVER_BOUGHT;

SHORT.SetDefaultColor(Color.DOWNTICK);
SHORT.SetPaintingStrategy(PaintingStrategy.BOOLEAN_ARROW_DOWN);
LONG.SetDefaultColor(Color.UPTICK);
LONG.SetPaintingStrategy(PaintingStrategy.BOOLEAN_ARROW_UP);
