# DMI_ReversalTrigger
# WGRIFFITH2 (C) 2013

INPUT LENGTH = 10;
INPUT KPERIOD = 14;
INPUT DPERIOD = 3;
INPUT OVER_BOUGHT = 90;
INPUT OVER_SOLD = 10;
INPUT AVGVOL = 60;

DEF DMISTOCH = DMI_STOCHASTICEXTREME(LENGTH, KPERIOD, DPERIOD, OVER_BOUGHT, OVER_SOLD);

DEF FASTLINE = ROUND(SIMPLEMOVINGAVG(100*((CLOSE-LOWEST(LOW,KPERIOD))/(HIGHEST(HIGH,KPERIOD)-LOWEST(LOW,KPERIOD))), LENGTH = DPERIOD));

DEF ENTRY = DMISTOCH CROSSES ABOVE OVER_SOLD AND FASTLINE[1] < 20 AND RSIWILDER()[1] < 40 AND VOLUMEAVG(LENGTH = AVGVOL) > VOLUMEAVG(LENGTH = AVGVOL).VOLAVG;

DEF ROLLINGLOW = LOWEST(DATA = LOW(), LENGTH = 7)[1];
DEF STOPLOSS = (LOW <= ROLLINGLOW AND ENTRY IS FALSE);

DEF EXIT = DMISTOCH CROSSES BELOW OVER_BOUGHT OR STOPLOSS IS TRUE;

plot Below = EXIT;
Below.SetDefaultColor(Color.DOWNTICK);
Below.SetPaintingStrategy(PaintingStrategy.BOOLEAN_ARROW_DOWN);

plot Above = ENTRY;
Above.SetDefaultColor(Color.UPTICK);
Above.SetPaintingStrategy(PaintingStrategy.BOOLEAN_ARROW_UP);