##############STOPLMTTRIGGER###############
# WGRIFFITH2 (C) 2013

# LOOKING FOR ONLY THE ENTRY SIGNAL BASED ON THE STOPLIMITTRIGGER STUDY; THIS IS USED IN THE SCANS AND WATCHLIST

INPUT SIDE = "LONG";
INPUT PERIODS = 3; # LAST NUMBER OF CANDLESTICKS
INPUT ATR = 3.5; # ATR FACTOR
INPUT OVER_BOUGHT = 40;
INPUT AVGVOL = 50;

# DEFINING ENTRY
DEF KPERIOD = 14;
DEF DPERIOD = 3;
DEF FASTLINE = ROUND(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD));
#DEF SLOWLINE = ROUND(SIMPLEMOVINGAVG(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD), LENGTH = DPERIOD));

DEF NEW_PERIOD = PERIODS - 1;
DEF PERFORMANCE = CLOSE > CLOSE[250];
DEF CHANGE = CLOSE > CLOSE[1];
DEF BUYSIGNAL = VOLUMEAVG(LENGTH = AVGVOL) > VOLUMEAVG(LENGTH = AVGVOL).VOLAVG AND FASTLINE > FASTLINE[1] AND CHANGE IS TRUE;
DEF THREEOUT = (THREEINSIDEUP() IS TRUE OR THREEOUTSIDEUP() IS TRUE OR THREEWHITESOLDIERS() IS TRUE);
DEF ENTRY = (BUYSIGNAL IS TRUE OR THREEOUT IS TRUE) AND PERFORMANCE IS TRUE AND FASTLINE < OVER_BOUGHT;

PLOT ABOVE = ENTRY;

ABOVE.SETDEFAULTCOLOR(CREATECOLOR(0, 255, 0));
ABOVE.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_UP);

#########################################