# EXITALERT
# DREWGRIFFITH15 (C) 2014

INPUT SIDE = {DEFAULT LONG, SHORT};
INPUT TARGET = 20;
INPUT TRAIL = 1;
INPUT DISPLACE = -1;

DEF STOP;
SWITCH (SIDE) {
CASE LONG:
    STOP = CLOSE < LOWEST(LOW()[-DISPLACE], TRAIL);
CASE SHORT:
    STOP = CLOSE > HIGHEST(HIGH()[-DISPLACE], TRAIL);
}

DEF LMT;
SWITCH (SIDE) {
CASE LONG:
    LMT = CLOSE > HIGHEST(HIGH()[-DISPLACE], TARGET);
CASE SHORT:
    LMT = CLOSE < LOWEST(LOW()[-DISPLACE], TARGET);
}

PLOT EXIT = STOP OR LMT;
EXIT.SETDEFAULTCOLOR(CREATECOLOR(255, 255, 255));
EXIT.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_DOWN);
