# EXITALERT
# WGRIFFITH2 (C) 2014

# THIS IS AN ALERT THAT STOCKS IS MOVING OUTSIDE OF NORMAL TRADING RANGE. DOES NOT NECESSARILY MEAN THAT IT IS A HARD EXIT ON EITHER SIDE BUT IT IS A SIGNAL TO MONITOR MUCH MORE CLOSELY.
# IF THE TARGET IS REACHED, WATCH IT CLOSELY AND SEE IF THERE'S A BREAKOUT. LOOK AT VOLUME FOR CONFIRMATION. OTHERWISE, TAKE PROFITS.

INPUT SIDE = {default LONG, SHORT};
INPUT TRAIL = 3;
INPUT TARGET = 20;

def VOL = volumeAvg() > VolumeAvg().VolAvg;

def LMT;
switch (SIDE) {
case LONG:
    LMT = HIGH >= HIGHEST(DATA = HIGH, LENGTH = TARGET)[1] AND !VOL;
case SHORT:
    LMT = LOW <= LOWEST(DATA = LOW, LENGTH = TARGET)[1] AND !VOL;
}

def STOP;
switch (SIDE) {
case LONG:
    STOP = LOW < LOWEST(DATA = LOW, LENGTH = TRAIL)[1];
case SHORT:
    STOP = HIGH > HIGHEST(DATA = HIGH, LENGTH = TRAIL)[1];
}

plot EXIT = STOP OR LMT;
EXIT.SetDefaultColor(CreateColor(255, 255, 255));
EXIT.SetPaintingStrategy(PaintingStrategy.BOOLEAN_ARROW_DOWN);