# EXITALERT
# WGRIFFITH2 (C) 2014

INPUT SIDE = {default LONG, SHORT};
INPUT TARGET = 20;
INPUT KPERIOD = 14;
INPUT DPERIOD = 3;

# STOCHASTICSLOW
DEF FASTLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD);
DEF SLOWLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD).SLOWD;

def STOP;
switch (SIDE) {
case LONG:
    STOP = FASTLINE[1] >= SLOWLINE[1] AND FASTLINE < SLOWLINE;
case SHORT:
    STOP = FASTLINE[1] <= SLOWLINE[1] AND FASTLINE > SLOWLINE;
}

def LMT;
switch (SIDE) {
case LONG:
    LMT = HIGH >= HIGHEST(DATA = HIGH, LENGTH = TARGET)[1];
case SHORT:
    LMT = LOW <= LOWEST(DATA = LOW, LENGTH = TARGET)[1];
}

plot EXIT = STOP OR LMT;
EXIT.SetDefaultColor(CreateColor(255, 255, 255));
EXIT.SetPaintingStrategy(PaintingStrategy.BOOLEAN_ARROW_DOWN);
