# GMMA
# WGRIFFITH2 (C) 2014

INPUT EMA1 = 3;
INPUT EMA2 = 5;
INPUT EMA3 = 8;
INPUT EMA4 = 10;
INPUT EMA5 = 12;
INPUT EMA6 = 15;
INPUT EMA7 = 30;
INPUT EMA8 = 35;
INPUT EMA9 = 40;
INPUT EMA10 = 45;
INPUT EMA11 = 50;
INPUT EMA12 = 60;

PLOT GMMA1 = EXPAVERAGE(Close,EMA1);
PLOT GMMA2 = EXPAVERAGE(Close,EMA2);
PLOT GMMA3 = EXPAVERAGE(Close,EMA3);
PLOT GMMA4 = EXPAVERAGE(Close,EMA4);
PLOT GMMA5 = EXPAVERAGE(Close,EMA5);
PLOT GMMA6 = EXPAVERAGE(Close,EMA6);
PLOT GMMA7 = EXPAVERAGE(Close,EMA7);
PLOT GMMA8 = EXPAVERAGE(Close,EMA8);
PLOT GMMA9 = EXPAVERAGE(Close,EMA9);
PLOT GMMA10 = EXPAVERAGE(Close,EMA10);
PLOT GMMA11 = EXPAVERAGE(Close,EMA11);
PLOT GMMA12 = EXPAVERAGE(Close,EMA12);

GMMA1.SetDefaultColor(GetColor(1));
GMMA2.SETDEFAULTCOLOR(GETCOLOR(1));
GMMA3.SETDEFAULTCOLOR(GETCOLOR(1));
GMMA4.SETDEFAULTCOLOR(GETCOLOR(1));
GMMA5.SETDEFAULTCOLOR(GETCOLOR(1));
GMMA6.SETDEFAULTCOLOR(GETCOLOR(1));
GMMA7.SETDEFAULTCOLOR(GETCOLOR(0));
GMMA8.SETDEFAULTCOLOR(GETCOLOR(0));
GMMA9.SETDEFAULTCOLOR(GETCOLOR(0));
GMMA10.SETDEFAULTCOLOR(GETCOLOR(0));
GMMA11.SETDEFAULTCOLOR(GETCOLOR(0));
GMMA12.SETDEFAULTCOLOR(GETCOLOR(0));