##############HEAVY ACTION###############
# WGRIFFITH2 (C) 2013
# THIS SCAN SUGGESTS HEAVY TRADING ACTION WITH A GOOD POINT OF ENTRY. DOES NOT FACTOR CANDLESTICK PATTERNS, BUT IT IS RECOMMENDED TO RELY ON BULLISH CANDLESTICK PATTERNS TO DETERMINE A POINT OF ENTRY
INPUT SIDE = "LONG";
INPUT PERIODS = 2; # LAST NUMBER OF CANDLESTICKS

INPUT KPERIOD = 14;
INPUT DPERIOD = 3;
INPUT OVER_BOUGHT = 80;
INPUT OVER_SOLD = 20;

# STOCHASTIC SLOW CALCULATION
DEF FASTLINE = ROUND(SIMPLEMOVINGAVG(100*((CLOSE-LOWEST(LOW,KPERIOD))/(HIGHEST(HIGH,KPERIOD)-LOWEST(LOW,KPERIOD))), LENGTH = DPERIOD));
DEF SLOWLINE = ROUND(SIMPLEMOVINGAVG(SIMPLEMOVINGAVG(100*((CLOSE-LOWEST(LOW,KPERIOD))/(HIGHEST(HIGH,KPERIOD)-LOWEST(LOW,KPERIOD))), LENGTH = DPERIOD), LENGTH = DPERIOD));

DEF NEW_PERIOD = PERIODS - 1;
DEF BUYSIGNAL = VOLUMEAVG(LENGTH = 20) > VOLUMEAVG(LENGTH = 20).VOLAVG AND FASTLINE <= 50 AND FASTLINE > SLOWLINE AND CLOSE > CLOSE[1];
DEF ENTRY = BUYSIGNAL IS TRUE;

PLOT ABOVE = ENTRY;

ABOVE.SETDEFAULTCOLOR(COLOR.UPTICK);
ABOVE.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_UP);

#########################################