# LONGEXITALERT
# WGRIFFITH2 (C) 2014

# THIS IS AN ALERT THAT STOCKS IS MOVING OUTSIDE OF NORMAL TRADING RANGE. DOES NOT NECESSARILY MEAN THAT IT IS A HARD EXIT ON EITHER SIDE BUT IT IS A SIGNAL TO MONITOR MUCH MORE CLOSELY.

INPUT KPERIOD = 14;
INPUT DPERIOD = 3;
INPUT MACD_FAST = 5;
INPUT MACD_SLOW = 35;
INPUT MACD_LEN = 3;
INPUT TAR = 20;

# STOCHASTICSLOW
DEF FASTLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD);
DEF SLOWLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD).SLOWD;

# MACD
DEF MACD = MACDHISTOGRAM("FAST LENGTH" = MACD_FAST, "SLOW LENGTH" = MACD_SLOW, "MACD LENGTH" = MACD_LEN);

# TEST
DEF GREENPRICE = FASTLINE >= SLOWLINE AND MACD >=0;
DEF REDPRICE = FASTLINE < SLOWLINE AND MACD < 0;

# TARGET
DEF TARGET = HIGHEST(DATA = HIGH, LENGTH = TAR);

# TRAILINGSTOP
def STOP = REDPRICE;

plot EXIT = STOP or TARGET;
EXIT.SetDefaultColor(CreateColor(255, 0, 0));
EXIT.SetPaintingStrategy(PaintingStrategy.BOOLEAN_ARROW_DOWN);