# LONGEXITALERT
# WGRIFFITH2 (C) 2014

# THIS IS AN ALERT THAT STOCKS IS MOVING OUTSIDE OF NORMAL TRADING RANGE. DOES NOT NECESSARILY MEAN THAT IT IS A HARD EXIT ON EITHER SIDE BUT IT IS A SIGNAL TO MONITOR MUCH MORE CLOSELY.

# DEFAULTS ARE A 40 DAY RSI SR FOR A TARGET, AND A 20 DAY LOW/HIGH FOR A STOPLOSS.

input SRLEN = 40;
input RSI_LENGTH = 14;
input STOPLOSSLEN = 20;
input STOPPRICE = LOW;

# RSI SUPPORT/RESISTANCE (SR)
def NETCHGAVG = WildersAverage(close - close[1], RSI_LENGTH);
def TOTCHGAVG = WildersAverage(AbsValue(close - close[1]), RSI_LENGTH);
def CHGRATIO = if TOTCHGAVG != 0 then NETCHGAVG / TOTCHGAVG else 0;
def RSI = Round(50 * (CHGRATIO + 1), NUMBEROFDIGITS = 0);
def RSI_HIGH = Round(Highest(RSI, LENGTH = SRLEN), NUMBEROFDIGITS = 0);
def TARGET = RSI == RSI_HIGH;

# TRAILINGSTOP
def STOP = close < Lowest(DATA = STOPPRICE, LENGTH = STOPLOSSLEN-1)[1];

plot EXIT = STOP or TARGET;
EXIT.SetDefaultColor(CreateColor(255, 0, 0));
EXIT.SetPaintingStrategy(PaintingStrategy.BOOLEAN_ARROW_DOWN);