#HTTP://WWW.CANDLESTICKER.COM/PATTERN.ASPX?LANG=EN&PATTERN=2111
(OPEN[1]-CLOSE[1])/(.001+(HIGH[1]-LOW[1]))>0.6 AND #LONG DARK CANDLE
(CLOSE-OPEN)/(.001+(HIGH-LOW))>0.6 AND #LONG WHITE CANDLE
(CLOSE[1]<OPEN) AND (OPEN[1] > OPEN) AND (OPEN[1]<CLOSE)