# ROLLINGTRAILINGSTOP
# WGRIFFITH2 (C) 2013

INPUT PERIODS = 3;
DEF ROLLINGLOW = LOWEST(DATA = LOW(), LENGTH = PERIODS)[1];

PLOT STOPLOSS = ROLLINGLOW[0];
STOPLOSS.SETDEFAULTCOLOR(CREATECOLOR(11, 0, 95));

##############################################