# ROLLINGTARGET
# WGRIFFITH2 (C) 2013

INPUT PERIODS = 15;
DEF ROLLINGHIGH = HIGHEST(DATA = HIGH(), LENGTH = PERIODS);

PLOT TARGET = ROLLINGHIGH;
TARGET.SETDEFAULTCOLOR(CREATECOLOR(11, 0, 95));

##############################################