# ROLLINGTRAILINGSTOP
# WGRIFFITH2 (C) 2013

INPUT PERIODS = 3;
DEF ROLLINGLOW = LOWEST(DATA = LOW(), LENGTH = PERIODS);

PLOT STOPLOSS = ROLLINGLOW;
STOPLOSS.SETDEFAULTCOLOR(CREATECOLOR(11, 0, 78));

##############################################