# ROLLINGTARGET
# WGRIFFITH2 (C) 2013

INPUT PERIODS = 14;
DEF ROLLINGHIGH = HIGHEST(DATA = HIGH(), LENGTH = PERIODS)[1];

PLOT TARGET = ROLLINGHIGH[0];
TARGET.SETDEFAULTCOLOR(CREATECOLOR(11, 0, 95));

##############################################