# RSI_SMA
# WGRIFFITH2 (C) 2013
#

DECLARE LOWER;

INPUT LENGTH = 14;
INPUT OVER_BOUGHT = 70;
INPUT OVER_SOLD = 30;
INPUT PRICE = CLOSE;
INPUT SMA_LENGTH = 12;

DEF NETCHGAVG = WILDERSAVERAGE(PRICE - PRICE[1], LENGTH);
DEF TOTCHGAVG = WILDERSAVERAGE(ABSVALUE(PRICE - PRICE[1]), LENGTH);
DEF CHGRATIO = IF TOTCHGAVG != 0 THEN NETCHGAVG / TOTCHGAVG ELSE 0;

DEF RSI_OUT = 50 * (CHGRATIO + 1);
DEF SMA = SIMPLEMOVINGAVG(PRICE = RSI_OUT, LENGTH = SMA_LENGTH);

PLOT RSI = RSI_OUT;
PLOT RSI_SMA = SMA;
PLOT OVERSOLD = OVER_SOLD;
PLOT OVERBOUGHT = OVER_BOUGHT;

RSI.DEFINECOLOR("OVERBOUGHT", GETCOLOR(5));
RSI.DEFINECOLOR("NORMAL", GETCOLOR(7));
RSI.DEFINECOLOR("OVERSOLD", GETCOLOR(1));
RSI.ASSIGNVALUECOLOR(IF RSI > OVER_BOUGHT THEN RSI.COLOR("OVERBOUGHT") ELSE IF RSI < OVER_SOLD THEN RSI.COLOR("OVERSOLD") ELSE RSI.COLOR("NORMAL"));
RSI_SMA.SETDEFAULTCOLOR(GETCOLOR(1));
OVERSOLD.SETDEFAULTCOLOR(GETCOLOR(8));
OVERBOUGHT.SETDEFAULTCOLOR(GETCOLOR(8));