# SHORTEXITALERT
# WGRIFFITH2 (C) 2014

# THIS IS AN ALERT THAT STOCKS IS MOVING OUTSIDE OF NORMAL TRADING RANGE. DOES NOT NECESSARILY MEAN THAT IT IS A HARD EXIT ON EITHER SIDE BUT IT IS A SIGNAL TO MONITOR MUCH MORE CLOSELY.

# DEFAULTS ARE A 40 DAY RSI SR FOR A TARGET, AND A 3 DAY LOW/HIGH FOR A STOPLOSS. IF THE TARGET IS REACHED, THEN SWITCH TO A LONGER RSI SR TARGET, AND A STOPLOSS OF A CLOSE BELOW/ABOVE THE PREVIOUS DAY. LET PROFITABLE BREAKOUTS RIDE UNTIL THERE'S A HINT OF IT STALLING OUT.

input SRLEN = 40;
input RSI_LENGTH = 14;
input STOPLOSSLEN = 20;
input STOPPRICE = HIGH;

# RSI SUPPORT/RESISTANCE (SR)
def NETCHGAVG = WildersAverage(close - close[1], RSI_LENGTH);
def TOTCHGAVG = WildersAverage(AbsValue(close - close[1]), RSI_LENGTH);
def CHGRATIO = if TOTCHGAVG != 0 then NETCHGAVG / TOTCHGAVG else 0;
def RSI = Round(50 * (CHGRATIO + 1), NUMBEROFDIGITS = 0);
def RSI_LOW = Round(Lowest(RSI, LENGTH = SRLEN), NUMBEROFDIGITS = 0);
def TARGET = RSI == RSI_LOW;

# TRAILINGSTOP
def STOP = close > Highest(DATA = STOPPRICE, LENGTH = STOPLOSSLEN-1)[1];

plot EXIT = STOP or TARGET;
EXIT.SetDefaultColor(CreateColor(255, 0, 0));
EXIT.SetPaintingStrategy(PaintingStrategy.BOOLEAN_ARROW_DOWN);