# STOCHASTICSLOWSMA
# DREWGRIFFITH15 (C) 2014

DECLARE LOWER;

# STOCHASTICSLOW WITH A SMA TO CONFIRM THE MOVE

INPUT KPERIOD = 14;
INPUT DPERIOD = 3;
INPUT SMA = 10;
INPUT OVER_BOUGHT = 85;
INPUT OVER_SOLD = 15;

PLOT FASTLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD);
PLOT STOCHASTIC_SMA = SIMPLEMOVINGAVG(FASTLINE,SMA);

FASTLINE.SETDEFAULTCOLOR(COLOR.MAGENTA);
FASTLINE.SETLINEWEIGHT(3);
STOCHASTIC_SMA.SETDEFAULTCOLOR(COLOR.CYAN);
STOCHASTIC_SMA.SETLINEWEIGHT(1);

PLOT OVERBOUGHT = OVER_BOUGHT;
OVERBOUGHT.SETDEFAULTCOLOR(COLOR.DARK_GRAY);

PLOT OVERSOLD = OVER_SOLD;
OVERSOLD.SETDEFAULTCOLOR(COLOR.DARK_GRAY);

FASTLINE.ASSIGNVALUECOLOR(IF FASTLINE > STOCHASTIC_SMA AND FASTLINE > OVERSOLD THEN COLOR.GREEN ELSE IF FASTLINE < STOCHASTIC_SMA AND FASTLINE < OVERBOUGHT THEN COLOR.RED ELSE COLOR.MAGENTA);
STOCHASTIC_SMA.ASSIGNVALUECOLOR(IF FASTLINE > STOCHASTIC_SMA AND FASTLINE > OVERSOLD THEN COLOR.GREEN ELSE IF FASTLINE < STOCHASTIC_SMA AND FASTLINE < OVERBOUGHT THEN COLOR.RED ELSE COLOR.MAGENTA);
