##############STOPLMTTRIGGER###############
# WGRIFFITH2 (C) 2013
# STUDY IS BUILT ON THE FOLLOWING PREMISE(S):
# DAVAS BOX BREAKOUT - NEW THREE DAY HIGH WITH HEAVY VOLUME
# NON-OVER-BOUGHT STOCK BASED ON STOCHASTIC SLOW
# LINEAR TREND QUALITY MUST BE POSITIVE

INPUT SIDE = "LONG";
INPUT PERIODS = 3;

# STOCHASTIC PARAMETERS
INPUT STOCHASTIC_LIMIT = 30;
INPUT KPERIOD = 14;
INPUT DPERIOD = 3;

# STOCHASTIC SLOW
DEF FASTLINE = ROUND(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD));
DEF SLOWLINE = ROUND(SIMPLEMOVINGAVG(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD), LENGTH = DPERIOD));
DEF GREENPRICE = FASTLINE > SLOWLINE AND FASTLINE <= STOCHASTIC_LIMIT;

# REQUIREMENTS
DEF NEW_PERIOD = PERIODS - 1;
DEF ROLLINGLOW = LOWEST(DATA = LOW(), LENGTH = PERIODS)[1];
DEF STOP = (LOW <= ROLLINGLOW);
DEF BREAKOUT = (CLOSE > HIGHEST(DATA = CLOSE, LENGTH = NEW_PERIOD)[1]) AND VOLUMEAVG(LENGTH = 20) > VOLUMEAVG(LENGTH = 20).VOLAVG;
DEF SHARES = ROUND(10000 / CLOSE);

DEF GREENLMT = BREAKOUT IS TRUE AND GREENPRICE IS TRUE;
DEF REDSTOPLOSS = (LOW <= ROLLINGLOW);

PLOT ABOVE = GREENLMT;
PLOT BELOW = REDSTOPLOSS;

BELOW.SETDEFAULTCOLOR(COLOR.DOWNTICK);
BELOW.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_DOWN);
ABOVE.SETDEFAULTCOLOR(COLOR.UPTICK);
ABOVE.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_UP);

#########################################