# SWINGTRADER
# WGRIFFITH2 (C) 2014

INPUT SIDE = {DEFAULT LONG, SHORT};
INPUT SHARES = 100;
INPUT TARGET = 20;
INPUT TRAIL = 3;
INPUT KPERIOD = 14;
INPUT DPERIOD = 3;
INPUT SMA = 10;
INPUT OVER_BOUGHT = 80;
INPUT OVER_SOLD = 20;

# STOCHASTICSLOW
DEF FASTLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD);
DEF SLOWLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD).SLOWD;
DEF STOCHASTIC_SMA = SIMPLEMOVINGAVG(FASTLINE,SMA);

DEF ENTRY;
SWITCH (SIDE) {

CASE LONG:
ENTRY = CLOSE >= HIGH[1]
AND FASTLINE > STOCHASTIC_SMA
AND FASTLINE > OVER_SOLD
AND LOWEST(FASTLINE, 2)[1] <= 20;

CASE SHORT:
ENTRY = CLOSE <= LOW[1]
AND FASTLINE < STOCHASTIC_SMA
AND FASTLINE < OVER_BOUGHT
AND HIGHEST(FASTLINE, 2)[1] >= 80;
}

def STOP;
switch (SIDE) {
case LONG:
    STOP = LOW <= LOWEST(DATA = LOW, LENGTH = TRAIL-1)[1];
case SHORT:
    STOP = HIGH >= HIGHEST(DATA = HIGH, LENGTH = TRAIL-1)[1];
}

def LMT;
switch (SIDE) {
case LONG:
    LMT = HIGH >= HIGHEST(DATA = HIGH, LENGTH = TARGET-1)[1];
case SHORT:
    LMT = LOW <= LOWEST(DATA = LOW, LENGTH = TARGET-1)[1];
}

PLOT EXIT = STOP OR LMT;

#DEF SHARES = ROUND(10000 / CLOSE);
DEF FOOBAR = SHARES;

#LONG POSITION:
ADDORDER(ORDERTYPE.BUY_TO_OPEN, ENTRY IS TRUE, TRADESIZE = FOOBAR, TICKCOLOR = GETCOLOR(0), ARROWCOLOR = GETCOLOR(0), NAME = "ENTRY");
ADDORDER(ORDERTYPE.SELL_TO_CLOSE, EXIT IS TRUE, TRADESIZE = FOOBAR, TICKCOLOR = GETCOLOR(1), ARROWCOLOR = GETCOLOR(1), NAME = "EXIT", PRICE = HIGH()[-1]);

##################################################
