# SWINGTRIGGER
# DREWGRIFFITH15 (C) 2014

DECLARE UPPER;

INPUT KPERIOD = 14;
INPUT DPERIOD = 3;
INPUT SMA = 10;
INPUT OVER_BOUGHT = 80;
INPUT OVER_SOLD = 20;

# STOCHASTICSLOW
DEF FASTLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD);
DEF SLOWLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD).SLOWD;
DEF STOCHASTIC_SMA = SIMPLEMOVINGAVG(FASTLINE,SMA);

DEF LONG =
CLOSE >= HIGH[1]
AND FASTLINE > STOCHASTIC_SMA
AND FASTLINE > OVER_SOLD
AND FASTLINE <=60;

DEF SHORT =
CLOSE <= LOW[1]
AND FASTLINE < STOCHASTIC_SMA
AND FASTLINE < OVER_BOUGHT
AND FASTLINE >=40;

PLOT BULL = LONG;
PLOT BEAR = SHORT;

PLOT RATING =
IF LONG THEN FASTLINE-FASTLINE[1]
ELSE IF SHORT THEN FASTLINE-FASTLINE[1]
ELSE 0;

BULL.SETDEFAULTCOLOR(CREATECOLOR(0, 255, 0));
BULL.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_UP);
BEAR.SETDEFAULTCOLOR(CREATECOLOR(255, 0, 0));
BEAR.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_DOWN);
RATING.Hide();
RATING.HideBubble();
