# SWINGALERT
# WGRIFFITH2 (C) 2014

# STOCHASTICSLOW
DEF KPERIOD = 14;
DEF DPERIOD = 3;
DEF FASTLINE = ROUND(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD));
DEF SLOWLINE = ROUND(SIMPLEMOVINGAVG(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD), LENGTH = DPERIOD));

# MACD
DEF MACD = MACDHISTOGRAM("FAST LENGTH" = 5, "SLOW LENGTH" = 35, "MACD LENGTH" = 5);

DEF GREENPRICE =
MACD > 0 AND
FASTLINE > SLOWLINE;

DEF REDPRICE =
MACD < 0 AND
FASTLINE < SLOWLINE;

# CHANGE PLOT AS NEEDED
PLOT LONGEXIT = !GREENPRICE AND CLOSE < LOW[1];
#PLOT LONGENTRY = GREENPRICE AND CLOSE > CLOSE[1];
#PLOT SHORTEXIT = !REDPRICE AND CLOSE > HIGH[1];
#PLOT SHORTENTRY = REDPRICE AND CLOSE < CLOSE[1];