# SWINGENTRYRATING
# WGRIFFITH2 (C) 2014

DECLARE LOWER;

INPUT KPERIOD = 14;
INPUT DPERIOD = 3;
INPUT EMA = 15;

# STOCHASTICSLOW
DEF FASTLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD);
DEF SLOWLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD).SLOWD;

DEF GMMA6 = EXPAVERAGE(Close,EMA);

# TEST
DEF GREENPRICE = FASTLINE >= SLOWLINE;
DEF REDPRICE = FASTLINE < SLOWLINE;
PLOT RATING =

IF
!REDPRICE
AND CLOSE >= GMMA6
AND (CLOSE[1] < GMMA6[1] OR OPEN < GMMA6)
AND FASTLINE <= 60
THEN FASTLINE-FASTLINE[1]

ELSE IF
!GREENPRICE
AND CLOSE <= GMMA6
AND (CLOSE[1] > GMMA6[1] OR OPEN > GMMA6)
AND FASTLINE >= 40
THEN FASTLINE-FASTLINE[1]

ELSE 0;