# SWINGENTRY
# WGRIFFITH2 (C) 2014

DECLARE UPPER;

INPUT KPERIOD = 40;
INPUT DPERIOD = 3;
INPUT RSI_SMA = 10;

# STOCHASTICSLOW
DEF FASTLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD);
DEF SLOWLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD).SLOWD;

#RSI
DEF NETCHGAVG = WILDERSAVERAGE(CLOSE - CLOSE[1], 14);
DEF TOTCHGAVG = WILDERSAVERAGE(ABSVALUE(CLOSE - CLOSE[1]), 14);
DEF CHGRATIO = IF TOTCHGAVG != 0 THEN NETCHGAVG / TOTCHGAVG ELSE 0;
DEF RSI = ROUND(50 * (CHGRATIO + 1), NUMBEROFDIGITS = 0);
DEF SMA = ROUND(SIMPLEMOVINGAVG(PRICE = RSI, LENGTH = RSI_SMA), 0);

# TEST
DEF GREENPRICE = FASTLINE >= SLOWLINE AND RSI >= SMA;
DEF REDPRICE = FASTLINE < SLOWLINE AND RSI <= SMA;

PLOT BULL =
GREENPRICE
AND CLOSE >= OHLC4[1]
AND LOWEST(FASTLINE[1], 2) <= 20;

PLOT BEAR =
REDPRICE
AND CLOSE <= OHLC4[1]
AND HIGHEST(FASTLINE[1], 2) >= 80;

BULL.SETDEFAULTCOLOR(CREATECOLOR(0, 255, 0));
BULL.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_UP);
BEAR.SETDEFAULTCOLOR(CREATECOLOR(255, 0, 0));
BEAR.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_DOWN);