# SWINGTREND
# WGRIFFITH2 (C) 2014

DEF PAINTBARS = YES;
INPUT kPERIOD1 = 20;
INPUT DPERIOD1 = 3;
INPUT kPERIOD2 = 40;
INPUT DPERIOD2 = 3;

# STOCHASTICSLOW
DEF FASTLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD1, "k period" = kPERIOD1);
DEF SLOWLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD1, "k period" = kPERIOD1).SLOWD;

# STOCHASTICSLOW
DEF FASTLINE2 = STOCHASTICSLOW("D PERIOD" = DPERIOD2, "k period" = kPERIOD2);
DEF SLOWLINE2 = STOCHASTICSLOW("D PERIOD" = DPERIOD2, "k period" = kPERIOD2).SLOWD;

# TEST
DEF GREENPRICE = FASTLINE >= SLOWLINE and FASTLINE2 >= SLOWLINE2;
DEF REDPRICE = FASTLINE < SLOWLINE and FASTLINE2 < SLOWLINE2;

PLOT BULLISH = GREENPRICE;
PLOT NEUTRAL = !GREENPRICE AND !REDPRICE;
PLOT BEARISH = REDPRICE;

BULLISH.SETDEFAULTCOLOR(COLOR.UPTICK);
BULLISH.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_POINTS);
BULLISH.SETLINEWEIGHT(3);
BULLISH.HIDE();
NEUTRAL.SETDEFAULTCOLOR(COLOR.GRAY);
NEUTRAL.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_POINTS);
NEUTRAL.SETLINEWEIGHT(3);
NEUTRAL.HIDE();
BEARISH.SETDEFAULTCOLOR(COLOR.DOWNTICK);
BEARISH.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_POINTS);
BEARISH.SETLINEWEIGHT(3);
BEARISH.HIDE();

DEFINEGLOBALCOLOR("BULLISH", COLOR.UPTICK);
DEFINEGLOBALCOLOR("NEUTRAL", COLOR.GRAY);
DEFINEGLOBALCOLOR("BEARISH", COLOR.DOWNTICK);
ASSIGNPRICECOLOR(IF !PAINTBARS THEN COLOR.CURRENT ELSE IF GREENPRICE THEN GLOBALCOLOR("BULLISH") ELSE IF REDPRICE THEN GLOBALCOLOR("BEARISH") ELSE GLOBALCOLOR("NEUTRAL"));