# SWINGTRADERLX
# WGRIFFITH2 (C) 2014

# ONLY USED ON LONG POSITIONS

INPUT SIDE = {DEFAULT LONG, SHORT};
INPUT SHARES = 100;
INPUT TARGET = 20;
INPUT KPERIOD = 14;
INPUT DPERIOD = 3;
INPUT MACD_FAST = 5;
INPUT MACD_SLOW = 35;
INPUT MACD_LEN = 5;
INPUT EMA6 = 12;

# STOCHASTICSLOW
DEF FASTLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD);
DEF SLOWLINE = STOCHASTICSLOW("D PERIOD" = DPERIOD, "K PERIOD" = KPERIOD).SLOWD;

# MACD
DEF MACD = MACDHISTOGRAM("FAST LENGTH" = MACD_FAST, "SLOW LENGTH" = MACD_SLOW, "MACD LENGTH" = MACD_LEN);

# TEST
DEF GREENPRICE = FASTLINE >= SLOWLINE AND MACD >=0.00;
DEF REDPRICE = FASTLINE < SLOWLINE AND MACD < 0.00;

DEF GMMA6 = CLOSE >= EXPAVERAGE(CLOSE,EMA6);

DEF ENTRY;
SWITCH (SIDE) {

CASE LONG:
ENTRY = GMMA6 AND !GMMA6[1]
AND GREENPRICE AND FASTLINE <= 80;

CASE SHORT:
ENTRY = !GMMA6 AND GMMA6[1]
AND REDPRICE AND FASTLINE >= 20;
}

DEF STOP;
SWITCH (SIDE) {
CASE LONG:
    STOP = FASTLINE[1] >= SLOWLINE[1] AND FASTLINE < SLOWLINE;
CASE SHORT:
    STOP = FASTLINE[1] <= SLOWLINE[1] AND FASTLINE > SLOWLINE;
}

DEF LMT;
SWITCH (SIDE) {
CASE LONG:
    LMT = HIGH >= HIGHEST(DATA = HIGH, LENGTH = TARGET)[1];
CASE SHORT:
    LMT = LOW <= LOWEST(DATA = LOW, LENGTH = TARGET)[1];
}

PLOT EXIT = STOP OR LMT;

#DEF SHARES = ROUND(10000 / CLOSE);
DEF FOOBAR = SHARES;

#LONG POSITION:
ADDORDER(ORDERTYPE.BUY_TO_OPEN, ENTRY IS TRUE, TRADESIZE = FOOBAR, TICKCOLOR = GETCOLOR(0), ARROWCOLOR = GETCOLOR(0), NAME = "ENTRY");
ADDORDER(ORDERTYPE.SELL_TO_CLOSE, EXIT IS TRUE, TRADESIZE = FOOBAR, TICKCOLOR = GETCOLOR(1), ARROWCOLOR = GETCOLOR(1), NAME = "EXIT", PRICE = OHLC4()[1]);

##################################################