# SWINGALERT
# WGRIFFITH2 (C) 2014

# STOCHASTICSLOW
DEF KPERIOD = 14;
DEF DPERIOD = 3;
DEF FASTLINE = ROUND(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD));
DEF SLOWLINE = ROUND(SIMPLEMOVINGAVG(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD), LENGTH = DPERIOD));

# MACD
DEF MACD = MACDHISTOGRAM("FAST LENGTH" = 5, "SLOW LENGTH" = 35, "MACD LENGTH" = 5);

DEF REDPRICE =
MACD < 0 AND
FASTLINE < SLOWLINE;

DEF BLUEPRICE = 
(MACD < 0
OR FASTLINE < SLOWLINE)
AND CLOSE < CLOSE[1]
AND CLOSE < OPEN;

PLOT BEARISH = REDPRICE OR BLUEPRICE;