# SWINGENTRY
# WGRIFFITH2 (C) 2013

DEF KPERIOD = 14;
DEF DPERIOD = 3;
DEF FASTLINE = ROUND(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD));
DEF SLOWLINE = ROUND(SIMPLEMOVINGAVG(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD), LENGTH = DPERIOD));

#DEF RSI = RSIWILDER(PRICE = CLOSE, LENGTH = 14);
#DEF SMA = SIMPLEMOVINGAVG(PRICE = RSI, LENGTH = 12);

# MACD
DEF MACD = MACDHISTOGRAM("FAST LENGTH" = 5, "SLOW LENGTH" = 35, "MACD LENGTH" = 5);

PLOT BULLISH = FASTLINE >= SLOWLINE
#AND MACD / LOWEST(MACD, LENGTH = 90) < 0.25
AND MACD >= 0
AND LOWEST(FASTLINE,3) < 25
AND CLOSE > SIMPLEMOVINGAVG()
AND CLOSE >= CLOSE[1];

BULLISH.SETDEFAULTCOLOR(CREATECOLOR(0, 255, 0));
BULLISH.SETPAINTINGSTRATEGY(PAINTINGSTRATEGY.BOOLEAN_ARROW_UP);

#########################################