# TECHNICALRANKING
# WGRIFFITH2 (C) 2013

#MODELED AFTER THE TECHNICAL RANKING FROM STOCKCHARTS
#HTTP://STOCKCHARTS.COM/SCHOOL/DOKU.PHP?ID=CHART_SCHOOL:TECHNICAL_INDICATORS:SCTR

INPUT PRICE = CLOSE;

DEF LTMA = MOVAVGEXPONENTIAL(LENGTH = 200, PRICE = PRICE);
DEF LTPR = ((PRICE-LTMA)/LTMA);

DEF MACD = MACDHistogram("fast length" = 5, "slow length" = 35, "macd length" = 5);
DEF SLOPE = (LinearRegressionSlope(price = MACD, length = 3));

DEF RSI = # ((RSIWilder()-RSIWilder()[1])/RSIWilder()[1]);
(100-rsiWilder())/1000;

DEF KPERIOD = 14;
DEF DPERIOD = 3;
DEF FASTLINE = ROUND(SIMPLEMOVINGAVG(100 * ((CLOSE - LOWEST(LOW, KPERIOD)) / (HIGHEST(HIGH, KPERIOD) - LOWEST(LOW, KPERIOD))), LENGTH = DPERIOD));
DEF SLOWLINE = ROUND(SIMPLEMOVINGAVG(SIMPLEMOVINGAVG(100*((CLOSE-LOWEST(LOW,KPERIOD))/(HIGHEST(HIGH,KPERIOD)-LOWEST(LOW,KPERIOD))), LENGTH = DPERIOD), LENGTH = DPERIOD));
DEF STOCH = ((FASTLINE-SLOWLINE)/SLOWLINE)/2;

DEF CMF = chaikinMoneyFlow();

PLOT TOTAL = LTPR+SLOPE+RSI+STOCH+CMF;
plot p1 = ltpr; plot p2 = slope; plot p3 = rsi; plot p5 = stoch; plot p6 = CMF;
##########################################################
