#HTTP://WWW.CANDLESTICKER.COM/BEARISH.ASP
#HTTP://WWW.CANDLESTICKER.COM/BULLISH.ASP
##################################################################
#CANDLESTICKER-BEARISH-HIGH1
#HIGH RELIABILITY
DARKCLOUDCOVER() OR KICKING().BEARISH OR ABANDONEDBABY().BEARISH OR EVENINGSTAR() OR EVENINGDOJISTAR()
##################################################################
#CANDLESTICKER-BEARISH-HIGH2
#HIGH RELIABILITY
THREEBLACKCROWS() OR THREEINSIDEDOWN() OR THREEOUTSIDEDOWN() OR ENGULFING().BEARISH
##################################################################
#CANDLESTICKER-BEARISH-MED3
#MED RELIABILITY
UPSIDEGAPTWOCROWS() OR HARAMICROSS().BEARISH OR ADVANCEBLOCK() OR DELIBERATION()
##################################################################
#CANDLESTICKER-BULLISH-HIGH1
#HIGH RELIABILITY
PIERCINGLINE() OR KICKING().BULLISH OR ABANDONEDBABY() OR MORNINGDOJISTAR() OR MORNINGSTAR()
##################################################################
#CANDLESTICKER-BULLISH-HIGH1
#HIGH RELIABILITY
THREEINSIDEUP() OR THREEOUTSIDEUP() OR THREEWHITESOLDIERS() OR ENGULFING().BULLISH
##################################################################
#CANDLESTICKER-BULLISH-MED3
#MED RELIABILITY
MEETINGLINES().BULLISH OR HARAMICROSS().BULLISH OR HOMINGPIGEON() OR THREESTARSINTHESOUTH()
##################################################################
#BULL-DMISTOCHASTICEXTREME
CROSSES(DMI_STOCHASTICEXTREME("HIGH LOW LENGTH" = 14),10,CROSSINGDIRECTION.ABOVE)
##################################################################
#STOCHASTICCROSSOVER
#STOCHASTICSLOW (WHEN THEY CROSS):
#EX: CROSSES(STOCHASTIC, 80, CROSSINGDIRECTION.ABOVE)
CROSSES(ROUND(SIMPLEMOVINGAVG(100*((CLOSE-LOWEST(LOW,14))/(HIGHEST(HIGH,14)-LOWEST(LOW,14))), LENGTH = 3)),ROUND(SIMPLEMOVINGAVG(SIMPLEMOVINGAVG(100*((CLOSE-LOWEST(LOW,14))/(HIGHEST(HIGH,14)-LOWEST(LOW,14))), LENGTH = 3), LENGTH = 3)), CROSSINGDIRECTION.ABOVE) OR
CROSSES(ROUND(SIMPLEMOVINGAVG(100*((CLOSE-LOWEST(LOW,14))/(HIGHEST(HIGH,14)-LOWEST(LOW,14))), LENGTH = 3)),ROUND(SIMPLEMOVINGAVG(SIMPLEMOVINGAVG(100*((CLOSE-LOWEST(LOW,14))/(HIGHEST(HIGH,14)-LOWEST(LOW,14))), LENGTH = 3), LENGTH = 3)), CROSSINGDIRECTION.BELOW)
##################################################################
# STOCKS GATHERING MOMENTUM
# 3 DAYS UP, PRICE AND VOLUME (BULLISH)
(CLOSE > CLOSE[1] AND
CLOSE [1] > CLOSE [2] AND
CLOSE [2] > CLOSE[3] AND
VOLUMEAVG() > VOLUMEAVG()[1] AND
VOLUMEAVG()[1] > VOLUMEAVG()[2] AND
VOLUMEAVG()[2] > VOLUMEAVG()[3])
OR
# 3 DAYS DOWN IN PRICE, 3 DAYS UP IN VOLUME (BEARISH REVERSAL)
(CLOSE < CLOSE[1] AND
CLOSE [1] < CLOSE [2] AND
CLOSE [2] < CLOSE[3] AND
VOLUMEAVG() > VOLUMEAVG()[1] AND
VOLUMEAVG()[1] > VOLUMEAVG()[2] AND
VOLUMEAVG()[2] > VOLUMEAVG()[3])
OR
# 3 DAYS DOWN IN PRICE, 3 DAYS DOWN IN VOLUME (BULLISH REVERSAL)
(CLOSE < CLOSE[1] AND
CLOSE [1] < CLOSE [2] AND
CLOSE [2] < CLOSE[3] AND
VOLUMEAVG() < VOLUMEAVG()[1] AND
VOLUMEAVG()[1] < VOLUMEAVG()[2] AND
VOLUMEAVG()[2] < VOLUMEAVG()[3])
##################################################################
# CONSOLIDATION BREAKOUT
# SYMMETRICAL CONSOLIDATION
HIGHEST(DATA = CLOSE, LENGTH = 30)[60]>HIGHEST(DATA = CLOSE, LENGTH = 30)[30] AND
HIGHEST(DATA = CLOSE, LENGTH = 30)[30]>HIGHEST(DATA = CLOSE, LENGTH = 30) AND
LOWEST(DATA = CLOSE, LENGTH = 30)[60]<LOWEST(DATA = CLOSE, LENGTH = 30)[30] AND
LOWEST(DATA = CLOSE, LENGTH = 30)[30]<LOWEST(DATA = CLOSE, LENGTH = 30) AND
# DECLINING VOLUME
VOLUMEAVG().VOLAVG[90] > VOLUMEAVG().VOLAVG AND
# HIGHER CLOSE TODAY
CLOSE()>CLOSE()[1] AND
# HEAVY VOLUME TODAY
VOLUMEAVG(LENGTH = 10) > VOLUMEAVG(LENGTH = 50).VOLAVG
##################################################################
# ASCENDING TRIANGLE BREAKOUT
# HIGHS ARE WITHIN 1% OF EACH OTHER
(ABSVALUE(HIGHEST(DATA = CLOSE, LENGTH = 30)[30]-HIGHEST(DATA = CLOSE, LENGTH = 30)[1])/HIGHEST(DATA = CLOSE, LENGTH = 30)[30] < .01 OR
 ABSVALUE(HIGHEST(DATA = CLOSE, LENGTH = 30)[60]-HIGHEST(DATA = CLOSE, LENGTH = 30)[1])/HIGHEST(DATA = CLOSE, LENGTH = 30)[60] < .01) AND
# BOTTOM SIDE CONSOLIDATION OVER LAST 90 DAYS
LOWEST(DATA = CLOSE, LENGTH = 30)[60]<LOWEST(DATA = CLOSE, LENGTH = 30)[30] AND
LOWEST(DATA = CLOSE, LENGTH = 30)[30]<LOWEST(DATA = CLOSE, LENGTH = 30) AND
# DECLINING VOLUME OVER LAST 60 DAYS
VOLUMEAVG().VOLAVG[60] > VOLUMEAVG().VOLAVG AND
# NEW 60 DAY HIGH
CLOSE()>HIGHEST(DATA = CLOSE, LENGTH = 60)[1] AND
# HEAVY VOLUME TODAY
VOLUMEAVG(LENGTH = 10) > VOLUMEAVG().VOLAVG
##################################################################
# DARVAS BOX BREAKOUT
(CLOSE > HIGHEST(DATA = HIGH, LENGTH = 8)[1] OR 
CLOSE < LOWEST(DATA = LOW, LENGTH = 8)[1]) AND
VOLUMEAVG(LENGTH = 10) > VOLUMEAVG(LENGTH = 10).VOLAVG
